### ISSUE TITLE
Sass function's aren't working

### ISSUE THREAD

**Issue by storrdev** [kriasoft/isomorphic-style-loader#35]
I'm attempting to use the sass function `darken()` on my links when using `:hover` however it seems that the function isn't running and just returns the function call:

my sass:

```
a:hover {
    color: darken($link-color, 30%);
}
```

the rule is appearing in my inspector like this:

```
nav a:hover {
    color: darken(#F2CB07, 30%);
}
```
##

**Comment by Ehesp** [comment]
https://github.com/kriasoft/react-starter-kit/issues/495

Pretty stupid to me naming files SASS and then not actually having the loader enabled by default. But should be an easy to sort issue.

**Comment by koistya** [comment]
@Ehesp the files are named `.scss` in order for editors to recognize Sass-like syntax in them and provide syntax highlighting and auto-complete functionality. The `sass-loader` is not included because it forces CSS files to be parsed two times, once by `sass-loader` and another time by `PostCSS`. Also, it enforces simple CSS code without fancy stuff that shouldn't not be in CSS anyways, but in React components instead.

Guys, what do you think about renaming `.scss` files in the starter kit back to `.css` and using a small set of PostCSS plugins to enable CSS3 features like [variables](https://www.w3.org/TR/css-variables/), [calc](http://www.w3.org/TR/css3-values/#calc) and [color functions](http://dev.w3.org/csswg/css-color/#modifying-colors). For example:

##### `style.css`

```css
:root {
  --link-color: red;
}

a:hover {
  color: color(var(--link-color) blackness(30%));
}
```

It seems like this syntax in `.css` files is supported in modern text editors and IDEs.
